### ISSUE TITLE
 Contract Upgrade Does Not Consider the Scenario of Committee Members Losing Their Private Keys

### ISSUE THREAD

**Issue by waterflier** [buckyos/SourceDAO#1]
When a committee member initiates a contract upgrade, only that member can cancel the upgrade or execute it based on the voting results. If the initiating committee member loses their private key following the upgrade's initiation, it seems this could potentially halt the entire upgrade process. Is this the case?

**Comment by weiqiushi** [comment]
No. When a committee member initiates a contract upgrade proposal, the "initiator" of the proposal is the proxy address of the contract. Not the actual tx sender himself.

When the proposal is approved, anyone can perform the upgrade operation by executing the contract's upgradeTo function through the hardhat framework.
At this time, verifyContractUpgrade is called by the contract code and msg.sender is the proxy address of the contract. If the new address is the same as the implement address in the proposal, the upgrade is excuted.

If the proposal is rejected, any committee member can cancel this upgrade. It is not limited to the member who initiated the proposal.

Also, there was a bug in the code of cancelContractUpgrade that was fixed in 16feb1a9
