### ISSUE TITLE
Need for Sequential Consistency in Contract Upgrade Proposals to Prevent Potential Concurrency Issues

### ISSUE THREAD

**Issue by waterflier** [buckyos/SourceDAO#2]
I believe that contract upgrades are critical operations, and we should prevent potential concurrency issues. For instance, Proposal 1 suggests upgrading the implementation to version 1.1, while Proposal 2 suggests upgrading the implementation to version 1.2. If the approval sequence turns out to be Proposal 2 followed by Proposal 1, the contract will actually be upgraded to version 1.1. From an implementation perspective, we should leverage the incremental nature of proposal IDs for protection. If a later upgrade proposal passes, earlier proposals should not be executable, even if they are passed.

**Comment by weiqiushi** [comment]
Currently, contract upgrades are serialized, so there are no two upgrade proposals for the same contract at the same time.
When an upgrade proposal is being voted on, it is not allowed to initiate a second upgrade proposal.

This is due to the design of UUPS, when upgrading a contract, you can use an _authorizeUpgrade() function to judge whether the upgrade can be passed, but when judging, the only information you can get is the agent address of the contract and the address of the new implementation.
